services:
  api:
    build:
      context: .
      target: production
    container_name: sps-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped